Selected Features:
- clicks
- input_forward
- input_backward
- input_left
- input_right
- session_duration
- completion_progress
- escaped
- riddle_1_mean
- riddle_1_std
- riddle_1_min
- riddle_1_max
- riddle_2_mean
- riddle_2_std
- riddle_2_min
- riddle_2_max
- riddle_5_mean
- riddle_3_mean
- riddle_3_std
- riddle_3_min
- riddle_3_count
- riddle_3_max
- riddle_4_mean
- riddle_4_std
- riddle_5_min
- riddle_4_min
- riddle_4_max
- riddle_4_count
- riddle_5_max
- riddle_5_std
- ommision_1
- riddle_5_count
- distraction_3_timestamps_first
- distraction_3_timestamps_mean
- ommision_2
- ommision_3
- ommision_4
- ommision_5
- commision_1
- commision_2
- distraction_1_timestamps_first
- commision_3
- distraction_1_timestamps_last
- distraction_3_timestamps_min
- distraction_3_timestamps_max
- distraction_3_timestamps_last
- distraction_2_timestamps_last
- distraction_2_timestamps_first
- has_adhd
