Selected Features:
- distraction_3_3
- riddle_3_count
- riddle_4_mean
- riddle_4_std
- distraction_1_2
- distraction_3_2
- riddle_4_count
- riddle_5_mean
- riddle_5_min
- riddle_5_max
- distraction_1_1
- ommision_1
- commision_5
- ommision_4
- ommision_5
- ommision_6
- commision_1
- commision_2
- commision_3
- riddle_3_min
- riddle_3_max
- distraction_2_1
- input_forward
- distraction_3_1
- input_left
- distraction_2_3
- session_duration
- completion_progress
- escaped
- riddle_1_mean
- distraction_1_3
- riddle_1_std
- riddle_1_max
- distraction_2_2
- riddle_2_mean
- riddle_2_std
- riddle_2_min
- riddle_2_max
- riddle_2_count
- riddle_1_min
- commision_4
- has_adhd
